version: "3.8"

services:
  app:
    build:
      context: .
    container_name: portfolio-app
    expose:
      - "8080"
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable
    depends_on:
      - db
    networks:
      - portfolio_network

  nginx:
    build:
      context: ./nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - portfolio_network

  db:
    image: postgres:13
    container_name: portfolio-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    expose:
      - "5432"
    networks:
      - portfolio_network

networks:
  portfolio_network:
    driver: bridge
