version: "3.8"

services:
  app:
    build:
      context: .
    container_name: portfolio-app
    expose:
      - "8080"  

  nginx:
    build:
      context: ./nginx
    container_name: nginx-proxy
    ports:
      - "80:80"  
    depends_on:
      - app

