---
- name: Install EPEL repository (CentOS only)
  yum:
    name: epel-release
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Install useful system tools (CentOS only)
  package:
    name: "{{ system_tools_packages }}"
    state: present
  when: ansible_facts['os_family'] == "RedHat"
  tags: [system_tools]

