---
- name: Install Docker 
  hosts: web01
  become: yes
  tasks:
    - name: Install required dependencies
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker CE repository
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      when: ansible_facts['distribution_version'] is version('8', '>=') 

    - name: Install Docker-ce
      yum:
        name: docker-ce
        state: present

    - name: Enable and start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Verify Docker installation
      command: docker --version
      register: docker_version
      changed_when: false

    - name: Show Docker version
      debug:
        var: docker_version.stdout

    - name: Gather facts
      ansible.builtin.setup:

    - name: Define Docker Compose version
      set_fact:
        docker_compose_version: "1.29.2"

    - name: Set Docker Compose URL
      set_fact:      
        docker_compose_url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_facts['system'] | lower }}-{{ ansible_facts['architecture'] | lower }}"
      

    - name: Download Docker Compse binary
      get_url:
        url: "{{ docker_compose_url }}"
        dest: /usr/local/bin/docker-compose
        mode: 'u+x'

    - name: Create symlink to docker-compose in /usr/bin
      file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link
       

    - name: Verify Docker Compose Installation
      command: docker-compose --version
      register: compose_version
      changed_when: false

    - name: Show Docker Compose version
      debug:
        var: compose_version.stdout      


          
