---
- name: Ensure curl is installed
  ansible.builtin.yum:
    name: curl
    state: present

- name: Download Go tarball
  ansible.builtin.get_url:
    url: "{{ go_download_url }}"
    dest: "/tmp/go{{ go_version }}.tar.gz"
    mode: '0644'

- name: Remove any existing Go installation
  ansible.builtin.file:
    path: "{{ go_install_dir }}/go"
    state: absent

- name: Extract Go tarball
  ansible.builtin.unarchive:
    src: "/tmp/go{{ go_version }}.tar.gz"
    dest: "{{ go_install_dir }}"
    remote_src: yes

- name: Set up Go environment
  ansible.builtin.template:
    src: go_env.sh.j2
    dest: /etc/profile.d/go_env.sh
    mode: '0755'

- name: Verify Go installation
  ansible.builtin.command: "{{ go_bin_path }}/go version"
  register: go_version_output
  changed_when: false
  failed_when: go_version_output.rc != 0

- name: Show installed Go version
  ansible.builtin.debug:
    msg: "Installed Go version: {{ go_version_output.stdout }}"

