all:
  children:
    webservers:
      hosts:
        web01:
          ansible_host: 172.31.33.130
    devservers:
      hosts:
        dev01:
          ansible_host: 172.31.28.229

  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: /home/ubuntu/portfolio_app/ansible/secrets/client-key.pem  
    ansible_python_interpreter: /usr/bin/python3.9

