---
- name: Setup DevServer environment
  hosts: devservers
  become: yes
  roles:  
    - role: docker
      tags: [docker]        
    - role: docker_compose
      tags: [docker_compose]
    - role: nginx
      tags: [nginx]
        #- role: system_tools
        #tags: [system_tools]
    - role: golang
      tags: [go]    
