# Używamy obrazu bazowego NGINX z Alpine Linux
FROM nginx:alpine

# Kopiujemy naszą niestandardową konfigurację NGINX
COPY default.conf /etc/nginx/conf.d/default.conf

# Wystawiamy port 80, na którym NGINX będzie nasłuchiwał
EXPOSE 80

