name: Stop Application

on:
  workflow_dispatch:

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Stop App via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: stefan
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/stefan/domain/portfolio_app
            docker compose down
            echo "The application has stopped."
