name: Deploy to Web Server

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repozytorium
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker Buildx (przydatne do budowy obrazów)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Logowanie do GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}   
          password: ${{ secrets.GHCR_TOKEN }}  

      # Budowanie obrazu Docker
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/mstefn/portfolio_app:latest .

      # Pushowanie obrazu do GitHub Container Registry
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/mstefn/portfolio_app:latest

      # Ustawienie klucza SSH i konfiguracja połączenia z serwerem
      - name: Set up SSH key
        run: |
          # Utwórz folder na klucze SSH
          mkdir -p ~/.ssh
          
          # Zapisz klucz do pliku id_rsa (klucz nie jest wyświetlany w logach)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Dodaj fingerprint do known_hosts
          ssh-keyscan -H ${{ secrets.WEB01_HOST }} >> ~/.ssh/known_hosts

          # Testowanie połączenia SSH (klucz nie będzie wyświetlany)
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.WEB_SERVER_USER }}@${{ secrets.WEB01_HOST }} 'echo "Connection successful"'

      # Zatrzymywanie istniejących kontenerów na serwerze
      - name: Stop running containers on the web server
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.WEB_SERVER_USER }}@${{ secrets.WEB01_HOST }} 'docker-compose -f /home/ec2-user/portfolio-deploy/docker-compose.yml down'

      # Pobieranie nowego obrazu Docker z GHCR na serwerze
      - name: Pull the Docker image from GHCR on Web Server
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.WEB_SERVER_USER }}@${{ secrets.WEB01_HOST }} 'docker pull ghcr.io/mstefn/portfolio_app:latest'

      # Uruchomienie nowego kontenera na serwerze
      - name: Deploy the app on Web Server
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.WEB_SERVER_USER }}@${{ secrets.WEB01_HOST }} 'docker-compose -f /home/ec2-user/portfolio-deploy/docker-compose.yml up -d'
